name       : quakespasm
version    : 0.92.1
release    : 1
source     :
    - https://ufpr.dl.sourceforge.net/project/quakespasm/Source/quakespasm-0.92.1.tgz : 00045ab6c496f99a24cdb3c97815a9f9d39b91f9d8c05b5063c4ea939e641e6e
license    : GPL-2.0
component  : games.action
summary    : A *Nix friendly Quake Engine based on the SDL port of the popular FitzQuake
description: |
    QuakeSpasm is a modern, cross-platform Quake engine based on FitzQuake
    It includes support for 64 bit CPUs and custom music playback, a new
    sound driver, some graphical niceities, and numerous bug-fixes and other
    improvements.
    Quakespasm utilizes either the SDL or SDL2 frameworks, so choose which
    one works best for you. SDL is probably less buggy, but SDL2 has nicer
    features and smoother mouse input - though no CD support.
    Game data must be placed in ~/.quakespasm/id1.
builddeps  :
    - pkgconfig(flac)
    - pkgconfig(gl)
    - pkgconfig(libmikmod)
    - pkgconfig(opusfile)
    - pkgconfig(sdl2)
    - pkgconfig(vorbis)
    - libmad-devel
build      : |
    %make -C Quake \
             DO_USERDIRS=1 \
             USE_SDL2=1 \
             USE_CODEC_FLAC=1 \
             USE_CODEC_OPUS=1 \
             USE_CODEC_MIKMOD=1 \
             USE_CODEC_UMX=1
install    : |
    install -Dm755 Quake/quakespasm $installdir/usr/bin/quakespasm
    install -Dm644 Misc/QuakeSpasm_512.png $installdir/usr/share/pixmaps/quakespasm.png
    install -Dm644 $pkgfiles/quakespasm.desktop $installdir/usr/share/applications/quakespasm.desktop
