name       : quakespasm
version    : 0.94.3
release    : 10
source     :
    - https://sourceforge.net/projects/quakespasm/files/Source/quakespasm-0.94.3.tar.gz : 3e95f6d3e5c7205e1a468b04aca1a7ca55c8a9d32d1b751bb22ef4ccd1bd0ead
license    : GPL-2.0-or-later
component  : games.action
homepage   : http://quakespasm.sourceforge.net/
summary    : A *Nix friendly Quake Engine based on the SDL port of the popular FitzQuake
description: |
    QuakeSpasm is a modern, cross-platform Quake engine based on FitzQuake.
    It includes support for 64 bit CPUs and custom music playback, a new sound driver, some graphical niceities, and numerous bug-fixes and other improvements.
    Game data must be placed in ~/.quakespasm/id1.
builddeps  :
    - pkgconfig(flac)
    - pkgconfig(gl)
    - pkgconfig(libmikmod)
    - pkgconfig(libmpg123)
    - pkgconfig(opusfile)
    - pkgconfig(sdl2)
    - pkgconfig(vorbis)
build      : |
    %make -C Quake \
             DO_USERDIRS=1 \
             MP3LIB=mpg123 \
             USE_CODEC_FLAC=1 \
             USE_CODEC_MIKMOD=1 \
             USE_CODEC_OPUS=1 \
             USE_CODEC_UMX=1 \
             USE_SDL2=1
install    : |
    install -Dm00755 Quake/quakespasm $installdir/usr/bin/quakespasm
    install -Dm00644 Misc/QuakeSpasm_512.png $installdir/usr/share/pixmaps/quake.png
    install -Dm00644 $pkgfiles/quakespasm.desktop $installdir/usr/share/applications/quakespasm.desktop
